default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: taskmaster_development
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: taskmaster_test
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  <<: *default
  database: taskmaster_production
  username: taskmaster
  password: <%= ENV["TASKMASTER_DATABASE_PASSWORD"] %>